# Generated by Django 4.1.7 on 2023-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Rather not say')], max_length=1, null=True, verbose_name='Sex')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
