# Generated by Django 4.1.7 on 2023-02-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateTimeField(blank=True, null=True, verbose_name='Date of collection')),
                ('diagnosis_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Diagnosis Code')),
                ('type', models.CharField(blank=True, choices=[('B', 'biopsy'), ('SR', 'surgical resection'), ('O', 'Other')], max_length=50, null=True, verbose_name='Type')),
                ('origin', models.CharField(blank=True, choices=[('B', 'blood'), ('T', 'tissue'), ('U', 'urine'), ('S', 'stool'), ('F', 'fluid'), ('O', 'Other')], max_length=50, null=True, verbose_name='Site of Origin')),
                ('symptoms', models.CharField(blank=True, max_length=800, null=True)),
                ('comments', models.CharField(blank=True, max_length=800, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='sample.patient')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
