# Generated by Django 4.1.7 on 2023-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
