# Generated by Django 4.1.7 on 2023-03-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_sample_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='human_label',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True, verbose_name='Human label'),
        ),
        migrations.AddField(
            model_name='sample',
            name='predicted_label',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True, verbose_name='Predicted Label'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='origin',
            field=models.CharField(blank=True, choices=[('B', 'blood'), ('T', 'tissue'), ('U', 'urine'), ('S', 'stool'), ('F', 'fluid'), ('O', 'other')], max_length=50, null=True, verbose_name='Site of Origin'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.CharField(blank=True, choices=[('B', 'biopsy'), ('SR', 'surgical resection'), ('O', 'other')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
