# Generated by Django 4.1.7 on 2023-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_sample_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.CharField(blank=True, choices=[('biopsy', 'biopsy'), ('surgical resection', 'surgical resection'), ('other', 'other')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
