# Generated by Django 4.1.7 on 2023-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_alter_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='annotations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='human_label',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True, verbose_name='Human Label'),
        ),
    ]
