# Generated by Django 4.1.7 on 2023-03-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_alter_sample_owner_sharedcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedcomment',
            old_name='receiverComment',
            new_name='receiver_comment',
        ),
        migrations.RenameField(
            model_name='sharedcomment',
            old_name='senderComment',
            new_name='sender_comment',
        ),
    ]
